plugin: aws_ec2
aws_profile: "default"
regions:
  - "us-east-1"
keyed_groups:
  - key: tags.Name
  - key: tags.Game
filters:
  instance-state-name: running
hostnames:
  - ip-address
compose:
  ansible_host: public_ip_address
